const categoryAliases: Record<string, string> = {
  Prayer: "Prayers & Devotions",
  Prayers: "Prayers & Devotions",
  "Prayer & Devotion": "Prayers & Devotions",
  "How to Pray": "Prayers & Devotions",
  "Novena & Prayer": "Prayers & Devotions",
  Devotions: "Prayers & Devotions",
  "Catholic Devotions": "Prayers & Devotions",
  "Devotions & Sacramentals": "Prayers & Devotions",
  Doctrine: "Catholic Doctrine",
  "Formation & Doctrine": "Catholic Doctrine",
  Theology: "Catholic Doctrine",
  "Doctrine & Morality": "Catholic Doctrine",
  "Morality & Life": "Catholic Doctrine",
  Saints: "Saints & Intercession",
  "Saints & Feast Days": "Saints & Intercession",
  "Saints & Healing": "Saints & Intercession",
  "Saints & Miracles": "Saints & Intercession",
  Vocation: "Vocations",
  "Marriage & Family": "Family & Parenting",
  "Relationships & Family": "Family & Parenting",
  Family: "Family & Parenting",
  "Mental Health": "Mental Health & Faith",
  Liturgy: "Liturgy & Worship",
  "Liturgical Year": "Liturgy & Worship",
  Sacraments: "Mass & Sacraments",
  Formation: "Becoming Catholic",
  Popes: "Catholic History",
};

export const getCanonicalCategory = (category: string) => categoryAliases[category] ?? category;
