/**
 * Central interlink map for Guide Catholic
 * Maps anchor text phrases → internal URLs
 * Used to add contextual internal links within article text
 *
 * Priority: highest-traffic articles link to related high-value pages
 */

export const INTERLINK_MAP: Record<string, string> = {
  // GSC St. Michael's Lent 2026 cluster
"St Michael's Lent Novena Day 1": "/blog/st-michaels-lent-novena-day-1-august-15-2026/",
  "Day 1 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-1-august-15-2026/",
  "St Michael's Lent Novena Day 2": "/blog/st-michaels-lent-novena-day-2-august-16-2026/",
  "Day 2 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-2-august-16-2026/",
  "St Michael's Lent Novena Day 3": "/blog/st-michaels-lent-novena-day-3-august-17-2026/",
  "Day 3 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-3-august-17-2026/",
  "St Michael's Lent Novena Day 4": "/blog/st-michaels-lent-novena-day-4-august-18-2026/",
  "Day 4 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-4-august-18-2026/",
  "St Michael's Lent Novena Day 5": "/blog/st-michaels-lent-novena-day-5-august-19-2026/",
  "Day 5 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-5-august-19-2026/",
  "St Michael's Lent Novena Day 6": "/blog/st-michaels-lent-novena-day-6-august-20-2026/",
  "Day 6 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-6-august-20-2026/",
  "St Michael's Lent Novena Day 7": "/blog/st-michaels-lent-novena-day-7-august-21-2026/",
  "Day 7 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-7-august-21-2026/",
  "St Michael's Lent Novena Day 8": "/blog/st-michaels-lent-novena-day-8-august-22-2026/",
  "Day 8 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-8-august-22-2026/",
  "St Michael's Lent Novena Day 9": "/blog/st-michaels-lent-novena-day-9-august-23-2026/",
  "Day 9 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-9-august-23-2026/",
  "St Michael's Lent Novena Day 10": "/blog/st-michaels-lent-novena-day-10-august-24-2026/",
  "Day 10 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-10-august-24-2026/",
  "St Michael's Lent Novena Day 11": "/blog/st-michaels-lent-novena-day-11-august-25-2026/",
  "Day 11 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-11-august-25-2026/",
  "St Michael's Lent Novena Day 12": "/blog/st-michaels-lent-novena-day-12-august-26-2026/",
  "Day 12 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-12-august-26-2026/",
  "St Michael's Lent Novena Day 13": "/blog/st-michaels-lent-novena-day-13-august-27-2026/",
  "Day 13 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-13-august-27-2026/",
  "St Michael's Lent Novena Day 14": "/blog/st-michaels-lent-novena-day-14-august-28-2026/",
  "Day 14 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-14-august-28-2026/",
  "St Michael's Lent Novena Day 15": "/blog/st-michaels-lent-novena-day-15-august-29-2026/",
  "Day 15 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-15-august-29-2026/",
  "St Michael's Lent Novena Day 16": "/blog/st-michaels-lent-novena-day-16-august-30-2026/",
  "Day 16 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-16-august-30-2026/",
  "St Michael's Lent Novena Day 17": "/blog/st-michaels-lent-novena-day-17-august-31-2026/",
  "Day 17 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-17-august-31-2026/",
  "St Michael's Lent Novena Day 18": "/blog/st-michaels-lent-novena-day-18-september-1-2026/",
  "Day 18 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-18-september-1-2026/",
  "St Michael's Lent Novena Day 19": "/blog/st-michaels-lent-novena-day-19-september-2-2026/",
  "Day 19 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-19-september-2-2026/",
  "St Michael's Lent Novena Day 20": "/blog/st-michaels-lent-novena-day-20-september-3-2026/",
  "Day 20 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-20-september-3-2026/",
  "St Michael's Lent Novena Day 21": "/blog/st-michaels-lent-novena-day-21-september-4-2026/",
  "Day 21 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-21-september-4-2026/",
  "St Michael's Lent Novena Day 22": "/blog/st-michaels-lent-novena-day-22-september-5-2026/",
  "Day 22 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-22-september-5-2026/",
  "St Michael's Lent Novena Day 23": "/blog/st-michaels-lent-novena-day-23-september-6-2026/",
  "Day 23 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-23-september-6-2026/",
  "St Michael's Lent Novena Day 24": "/blog/st-michaels-lent-novena-day-24-september-7-2026/",
  "Day 24 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-24-september-7-2026/",
  "St Michael's Lent Novena Day 25": "/blog/st-michaels-lent-novena-day-25-september-8-2026/",
  "Day 25 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-25-september-8-2026/",
  "St Michael's Lent Novena Day 26": "/blog/st-michaels-lent-novena-day-26-september-9-2026/",
  "Day 26 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-26-september-9-2026/",
  "St Michael's Lent Novena Day 27": "/blog/st-michaels-lent-novena-day-27-september-10-2026/",
  "Day 27 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-27-september-10-2026/",
  "St Michael's Lent Novena Day 28": "/blog/st-michaels-lent-novena-day-28-september-11-2026/",
  "Day 28 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-28-september-11-2026/",
  "St Michael's Lent Novena Day 29": "/blog/st-michaels-lent-novena-day-29-september-12-2026/",
  "Day 29 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-29-september-12-2026/",
  "St Michael's Lent Novena Day 30": "/blog/st-michaels-lent-novena-day-30-september-13-2026/",
  "Day 30 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-30-september-13-2026/",
  "St Michael's Lent Novena Day 31": "/blog/st-michaels-lent-novena-day-31-september-14-2026/",
  "Day 31 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-31-september-14-2026/",
  "St Michael's Lent Novena Day 32": "/blog/st-michaels-lent-novena-day-32-september-15-2026/",
  "Day 32 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-32-september-15-2026/",
  "St Michael's Lent Novena Day 33": "/blog/st-michaels-lent-novena-day-33-september-16-2026/",
  "Day 33 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-33-september-16-2026/",
  "St Michael's Lent Novena Day 34": "/blog/st-michaels-lent-novena-day-34-september-17-2026/",
  "Day 34 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-34-september-17-2026/",
  "St Michael's Lent Novena Day 35": "/blog/st-michaels-lent-novena-day-35-september-18-2026/",
  "Day 35 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-35-september-18-2026/",
  "St Michael's Lent Novena Day 36": "/blog/st-michaels-lent-novena-day-36-september-19-2026/",
  "Day 36 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-36-september-19-2026/",
  "St Michael's Lent Novena Day 37": "/blog/st-michaels-lent-novena-day-37-september-20-2026/",
  "Day 37 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-37-september-20-2026/",
  "St Michael's Lent Novena Day 38": "/blog/st-michaels-lent-novena-day-38-september-21-2026/",
  "Day 38 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-38-september-21-2026/",
  "St Michael's Lent Novena Day 39": "/blog/st-michaels-lent-novena-day-39-september-22-2026/",
  "Day 39 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-39-september-22-2026/",
  "St Michael's Lent Novena Day 40": "/blog/st-michaels-lent-novena-day-40-september-23-2026/",
  "Day 40 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-40-september-23-2026/",
  "St Michael's Lent Novena Day 41": "/blog/st-michaels-lent-novena-day-41-september-24-2026/",
  "Day 41 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-41-september-24-2026/",
  "St Michael's Lent Novena Day 42": "/blog/st-michaels-lent-novena-day-42-september-25-2026/",
  "Day 42 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-42-september-25-2026/",
  "St Michael's Lent Novena Day 43": "/blog/st-michaels-lent-novena-day-43-september-26-2026/",
  "Day 43 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-43-september-26-2026/",
  "St Michael's Lent Novena Day 44": "/blog/st-michaels-lent-novena-day-44-september-27-2026/",
  "Day 44 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-44-september-27-2026/",
  "St Michael's Lent Novena Day 45": "/blog/st-michaels-lent-novena-day-45-september-28-2026/",
  "Day 45 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-45-september-28-2026/",
  "St Michael's Lent Novena Day 46": "/blog/st-michaels-lent-novena-day-46-september-29-2026/",
  "Day 46 St Michael's Lent Novena": "/blog/st-michaels-lent-novena-day-46-september-29-2026/",
  "michaelmas 2026": "/blog/michaelmas-2026-when-is-it/",
  "feast of st michael the archangel 2026": "/blog/feast-of-st-michael-the-archangel-2026/",
  "feast of the archangels 2026": "/blog/feast-of-the-archangels-september-29-2026/",
  "st michael's lent 2026": "/blog/st-michaels-lent-2026/",
  "St Michael's Lent 2026": "/blog/st-michaels-lent-2026/",
  "st michael lent 2026": "/blog/st-michael-lent-2026/",
  "St Michael Lent 2026": "/blog/st-michael-lent-2026/",
  "saint michael's lent 2026": "/blog/saint-michaels-lent-2026/",
  "Saint Michael's Lent 2026": "/blog/saint-michaels-lent-2026/",
  "st. michael's lent 2026": "/blog/st-michaels-lent-2026-calendar/",
  "St. Michael's Lent 2026 Calendar": "/blog/st-michaels-lent-2026-calendar/",
  "st michaels lent 2026": "/blog/st-michaels-lent-meaning-2026/",
  "St Michaels Lent 2026 Explained": "/blog/st-michaels-lent-meaning-2026/",
  "saint michaels lent 2026": "/blog/saint-michaels-lent-prayers-2026/",
  "Saint Michaels Lent 2026 Prayers": "/blog/saint-michaels-lent-prayers-2026/",
  "saint michael lent 2026": "/blog/saint-michael-lent-2026/",
  "Saint Michael Lent 2026 for Beginners": "/blog/saint-michael-lent-2026/",

  // Rosary
  "the Rosary": "/blog/complete-rosary-guide/",
  "pray the Rosary": "/blog/complete-rosary-guide/",
  "praying the Rosary": "/blog/complete-rosary-guide/",
  "Holy Rosary": "/blog/rosary-complete-guide/",
  "Rosary mysteries": "/blog/rosary-mysteries-meditation/",

  // Sacraments
  "Sacrament of Reconciliation": "/blog/catholic-confession-guide/",
  "go to Confession": "/blog/how-to-go-to-confession/",
  "going to Confession": "/blog/how-to-go-to-confession/",
  "frequent Confession": "/blog/importance-confession/",
  "Confession times": "/blog/confession-times-near-me/",
  "the Eucharist": "/blog/complete-guide-to-the-eucharist/",
  "Real Presence": "/blog/eucharist-real-presence/",
  "Eucharistic adoration": "/blog/eucharistic-adoration/",
  "Eucharistic Adoration near me": "/blog/eucharistic-adoration-near-me/",
  "Holy Mass": "/blog/what-is-the-catholic-mass-guide/",
  "the Mass": "/blog/complete-guide-to-the-catholic-mass/",
  "attend Mass": "/blog/sunday-mass/",
  "Sunday Mass": "/blog/sunday-mass/",
  "Anointing of the Sick": "/blog/catholic-last-rites-explained/",
  "Last Rites": "/blog/catholic-last-rites-explained/",
  "Baptism": "/blog/catholic-baptism-explained/",
  "seven sacraments": "/blog/seven-sacraments/",

  // Prayer
  "Divine Mercy Chaplet": "/blog/divine-mercy-chaplet/",
  "Chaplet of Divine Mercy": "/blog/divine-mercy-chaplet/",
  "Lectio Divina": "/blog/lectio-divina/",
  "examination of conscience": "/blog/examination-of-conscience-guide/",
  "daily prayer": "/blog/catholic-daily-prayer-routine/",
  "morning prayer": "/blog/morning-prayer-catholic/",
  "night prayer": "/blog/night-prayer-catholic/",
  "intercessory prayer": "/blog/how-to-pray-intercessory-prayer/",
  "Liturgy of the Hours": "/blog/liturgy-of-the-hours-guide/",
  "Divine Office": "/blog/divine-office-laity/",
  "prayer for the sick": "/blog/catholic-prayer-for-the-sick/",
  "prayer for anxiety": "/blog/catholic-prayer-for-anxiety/",
  "prayer for protection": "/blog/catholic-prayer-for-protection/",
  "Prayer to Saint Michael": "/blog/saint-michael-prayer/",
  "St. Michael prayer": "/blog/saint-michael-prayer/",
  "Hail Mary": "/blog/hail-mary-prayer/",
  "Our Father": "/blog/our-father-prayer/",
  "Apostles' Creed": "/blog/apostles-creed-prayer/",
  "Glory Be": "/blog/glory-be-prayer/",
  "Guardian Angel Prayer": "/blog/guardian-angel-prayer/",
  "Come Holy Spirit": "/blog/come-holy-spirit-prayer/",
  "Holy Spirit prayer": "/blog/come-holy-spirit-prayer/",
  "Sign of the Cross": "/blog/sign-of-the-cross-catholic/",
  "grace after meals": "/blog/grace-after-meals-catholic/",
  "O My Jesus": "/blog/fatima-prayer-o-my-jesus/",
  "St. Michael Chaplet": "/blog/st-michael-chaplet-prayer/",
  "Seven Sorrows Rosary": "/blog/seven-sorrows-rosary-guide/",
  "Act of Faith": "/blog/act-of-faith-hope-charity/",
  "Act of Hope": "/blog/act-of-faith-hope-charity/",
  "Act of Charity": "/blog/act-of-faith-hope-charity/",
  "Regina Caeli": "/blog/regina-caeli-prayer/",
  "Litany of the Saints": "/blog/litany-of-the-saints-catholic/",
  "Divine Praises": "/blog/divine-praises-catholic/",
  "Jesus Prayer": "/blog/jesus-prayer-catholic/",
  "Anima Christi": "/blog/anima-christi-prayer/",
  "Hail Holy Queen": "/blog/hail-holy-queen-prayer/",
  "Salve Regina": "/blog/hail-holy-queen-prayer/",
  "Agnus Dei": "/blog/agnus-dei-prayer-catholic/",
  "Lamb of God": "/blog/agnus-dei-prayer-catholic/",
  "Eternal Rest": "/blog/eternal-rest-prayer-catholic/",
  "Requiem aeternam": "/blog/eternal-rest-prayer-catholic/",
  "Sub Tuum Praesidium": "/blog/sub-tuum-praesidium-prayer/",
  "Beatitudes": "/blog/beatitudes-catholic-explained/",
  "corporal works of mercy": "/blog/corporal-works-of-mercy-catholic/",
  "spiritual works of mercy": "/blog/spiritual-works-of-mercy-catholic/",
  "Magnificat": "/blog/magnificat-prayer-catholic/",
  "Te Deum": "/blog/te-deum-prayer-catholic/",
  "Palm Sunday": "/blog/palm-sunday-catholic-guide/",
  "Catholic cremation": "/blog/catholic-cremation-rules-usa/",
  "precepts of the Church": "/blog/precepts-of-the-catholic-church/",
  "Prayer of St. Francis": "/blog/prayer-of-st-francis-catholic/",
  "Litany of Humility": "/blog/litany-of-humility-catholic/",
  "novena": "/blog/how-to-pray-a-novena-guide/",
  "nine-day novena": "/blog/how-to-pray-a-novena-guide/",
  "St. Jude novena": "/blog/st-jude-novena-guide/",
  "St. Joseph novena": "/blog/st-joseph-novena-for-employment/",
  "St. Rita": "/blog/st-rita-novena-impossible-causes/",
  "Saint Rita": "/blog/st-rita-novena-impossible-causes/",
  "St. Monica": "/blog/st-monica-novena-for-children/",
  "Saint Monica": "/blog/st-monica-novena-for-children/",
  "Undoer of Knots": "/blog/undoer-of-knots-novena-guide/",
  "Mary Undoer of Knots": "/blog/undoer-of-knots-novena-guide/",
  "novena for marriage": "/blog/novena-for-marriage-catholic/",
  "novena before surgery": "/blog/novena-before-surgery-catholic/",
  "novena for financial help": "/blog/novena-for-financial-help-catholic/",
  "novena for clarity": "/blog/novena-for-clarity-catholic/",
  "Michaelmas": "/blog/michaelmas-2026-when-is-it/",
  "Feast of the Archangels": "/blog/feast-of-the-archangels-september-29-2026/",
  "200th pope": "/blog/200th-pope-who-was-it/",
  "Urban V": "/blog/pope-bl-urban-v/",
  "find my parish": "/blog/how-to-find-my-catholic-parish/",
  "pride root of all sin": "/blog/pride-root-of-sin-catholic/",
  "Litany of Loreto": "/blog/litany-of-loreto-catholic/",
  "Prayer of Abandonment": "/blog/prayer-of-abandonment-catholic/",
  "Spiritual Communion": "/blog/act-of-spiritual-communion-catholic/",
  "Act of Spiritual Communion": "/blog/act-of-spiritual-communion-catholic/",
  "St. Expedite": "/blog/st-expedite-novena-guide/",
  "novena for the dead": "/blog/novena-for-the-dead-catholic/",
  "novena for anxiety": "/blog/novena-for-anxiety-catholic/",
  "St. Anthony novena": "/blog/st-anthony-novena-lost-things/",
  "St. Gerard": "/blog/st-gerard-novena-pregnancy/",
  "novena for addiction": "/blog/novena-for-addiction-catholic/",
  "novena for exams": "/blog/novena-for-exams-catholic/",
  "St. Michael novena": "/blog/st-michael-novena-protection/",
  "St. Michael's Lent": "/blog/st-michaels-lent-2026/",
  "St Michael's Lent": "/blog/st-michaels-lent-2026/",
  "novena for fertility": "/blog/novena-for-fertility-catholic/",
  "Corpus Christi": "/blog/corpus-christi-feast-guide-catholic/",
  "Sacred Heart devotion": "/blog/sacred-heart-devotion-complete-guide/",
  "Assumption of Mary": "/blog/assumption-of-mary-catholic-guide/",
  "Queenship of Mary": "/blog/queenship-of-mary-catholic-guide/",
  "how long is RCIA": "/blog/how-long-is-rcia-process/",
  "godparent": "/blog/catholic-godparent-requirements-usa/",
  "First Communion": "/blog/what-age-first-communion-catholic-usa/",
  "organ donation": "/blog/can-catholics-donate-organs/",
  "cremated remains": "/blog/can-catholics-keep-ashes-at-home/",
  "list of popes": "/blog/list-of-all-popes-catholic-complete-guide/",
  "all popes": "/blog/list-of-all-popes-catholic-complete-guide/",
  "successors of Peter": "/blog/list-of-all-popes-catholic-complete-guide/",
"Bible Verses About Anxiety": "/blog/bible-verses-about-anxiety/",
  "Bible Verses About Strength": "/blog/bible-verses-about-strength/",
  "Bible Verses About Love": "/blog/bible-verses-about-love/",
  "Bible Verses About Hope": "/blog/bible-verses-about-hope/",
  "Bible Verses About Healing": "/blog/bible-verses-about-healing/",
  "Bible Verses About Faith": "/blog/bible-verses-about-faith/",
  "Bible Verses About Peace": "/blog/bible-verses-about-peace/",
  "Bible Verses About Depression": "/blog/bible-verses-about-depression/",
  "Bible Verses About Fear": "/blog/bible-verses-about-fear/",
  "Bible Verses About Protection": "/blog/bible-verses-about-protection/",
  "Bible Verses About Forgiveness": "/blog/bible-verses-about-forgiveness/",
  "Bible Verses About Prayer": "/blog/bible-verses-about-prayer/",
  "Bible Verses About Family": "/blog/bible-verses-about-family/",
  "Bible Verses About Marriage": "/blog/bible-verses-about-marriage/",
  "Bible Verses About Friendship": "/blog/bible-verses-about-friendship/",
  "Bible Verses for Anxiety and Fear": "/blog/bible-verses-for-anxiety-and-fear/",
  "Bible Verses for Strength During Hard Times": "/blog/bible-verses-for-strength-during-hard-times/",
  "Short Bible Verses About Strength": "/blog/short-bible-verses-about-strength/",
  "Short Bible Verses About Love": "/blog/short-bible-verses-about-love/",
  "Encouraging Bible Verses": "/blog/encouraging-bible-verses/",
  "Inspirational Bible Verses": "/blog/inspirational-bible-verses/",
  "Powerful Bible Verses": "/blog/powerful-bible-verses/",
  "Bible Verses for Difficult Times": "/blog/bible-verses-for-difficult-times/",
  "Bible Verses for Healing and Recovery": "/blog/bible-verses-for-healing-and-recovery/",
  "Bible Verses for Sleep": "/blog/bible-verses-for-sleep/",
  "Bible Verses for a Broken Heart": "/blog/bible-verses-for-a-broken-heart/",
  "Bible Verses for Grief": "/blog/bible-verses-for-grief/",
  "Bible Verses for Stress": "/blog/bible-verses-for-stress/",
  "Bible Verses for Success": "/blog/bible-verses-for-success/",
  "Bible Verses for New Beginnings": "/blog/bible-verses-for-new-beginnings/",
  "Bible Verses for Mothers": "/blog/bible-verses-for-mothers/",
  "Bible Verses for Fathers": "/blog/bible-verses-for-fathers/",
  "Bible Verses for Children": "/blog/bible-verses-for-children/",
  "Bible Verses for Women": "/blog/bible-verses-for-women/",
  "Bible Verses for Men": "/blog/bible-verses-for-men/",
  "Bible Verses About God's Love": "/blog/bible-verses-about-gods-love/",
  "Bible Verses About Trusting God": "/blog/bible-verses-about-trusting-god/",
  "Bible Verses About God's Plan": "/blog/bible-verses-about-gods-plan/",
  "Bible Verses About Happiness": "/blog/bible-verses-about-happiness/",
  "Bible Verses About Life": "/blog/bible-verses-about-life/",


  // Mary
  "Virgin Mary": "/blog/virgin-mary-complete-guide/",
  "Our Lady of Fatima": "/blog/our-lady-of-fatima-guide/",
  "Our Lady of Lourdes": "/blog/our-lady-of-lourdes-guide/",
  "Our Lady of Guadalupe": "/blog/our-lady-of-guadalupe-patroness-americas/",
  "Immaculate Conception": "/blog/immaculate-conception-guide/",
  "Marian devotion": "/blog/do-catholics-worship-mary/",

  // Saints
  "Saint Francis of Assisi": "/blog/saint-francis-of-assisi/",
  "St. Francis of Assisi": "/blog/saint-francis-of-assisi/",
  "Saint Thomas Aquinas": "/blog/saint-thomas-aquinas/",
  "St. Thomas Aquinas": "/blog/saint-thomas-aquinas/",
  "Saint Augustine": "/blog/saint-augustine-of-hippo/",
  "St. Augustine": "/blog/saint-augustine-of-hippo/",
  "Saint Padre Pio": "/blog/saint-padre-pio/",
  "Padre Pio": "/blog/saint-padre-pio/",
  "Saint Thérèse of Lisieux": "/blog/saint-therese-of-lisieux/",
  "St. Thérèse": "/blog/saint-therese-of-lisieux/",
  "Little Way": "/blog/saint-therese-of-lisieux/",
  "Saint John of the Cross": "/blog/saint-john-of-the-cross/",
  "St. John of the Cross": "/blog/saint-john-of-the-cross/",
  "Saint Teresa of Ávila": "/blog/saint-teresa-of-avila/",
  "St. Teresa of Ávila": "/blog/saint-teresa-of-avila/",
  "Saint Ignatius of Loyola": "/blog/saint-ignatius-of-loyola/",
  "St. Ignatius": "/blog/saint-ignatius-of-loyola/",
  "Saint Joseph": "/blog/saint-joseph-complete-guide/",
  "Saint Michael": "/blog/saint-michael-archangel/",
  "Saint Anthony": "/blog/saint-anthony-of-padua/",
  "Saint Maximilian Kolbe": "/blog/saint-maximilian-kolbe/",
  "Saint Joan of Arc": "/blog/saint-joan-of-arc/",
  "guardian angel": "/blog/guardian-angels/",
  "guardian angels": "/blog/guardian-angels/",
  "patron saint": "/blog/patron-saints-guide/",

  // Doctrine
  "Holy Trinity": "/blog/what-is-the-holy-trinity/",
  "the Trinity": "/blog/what-is-the-holy-trinity/",
  "original sin": "/blog/what-is-original-sin-catholic/",
  "purgatory": "/blog/what-is-purgatory/",
  "Purgatory": "/blog/what-is-purgatory/",
  "indulgences": "/blog/plenary-indulgence-guide/",
  "plenary indulgence": "/blog/plenary-indulgence-guide/",
  "apostolic succession": "/blog/did-jesus-found-the-catholic-church/",
  "Nicene Creed": "/blog/what-is-the-nicene-creed/",
  "natural law": "/blog/catholic-teaching-on-justice/",
  "sanctifying grace": "/blog/what-is-grace-catholic/",
  "grace": "/blog/what-is-grace-catholic/",
  "free will": "/blog/what-is-freedom-catholic/",
  "theological virtues": "/blog/what-is-charity-catholic/",
  "faith and works": "/blog/faith-and-works-catholic/",
  "spiritual warfare": "/blog/spiritual-warfare-catholic/",
  "dark night of the soul": "/blog/saint-john-of-the-cross/",
  "Dark Night of the Soul": "/blog/saint-john-of-the-cross/",

  // Spiritual Life
  "Spiritual Exercises": "/blog/saint-ignatius-of-loyola/",
  "discernment": "/blog/vocational-discernment-guide/",
  "spiritual direction": "/blog/catholic-spiritual-direction/",
  "contemplative prayer": "/blog/what-is-catholic-spirituality/",
  "Ignatian spirituality": "/blog/saint-ignatius-of-loyola/",
  "Carmelite spirituality": "/blog/what-is-catholic-spirituality/",
  "Benedictine spirituality": "/blog/what-is-catholic-spirituality/",
  "fasting": "/blog/catholic-fasting-rules/",
  "Lent": "/blog/lent-preparation-guide/",
  "Advent": "/blog/what-is-advent/",
  "Holy Week": "/blog/what-is-holy-week/",
  "Stations of the Cross": "/blog/stations-of-the-cross/",

  // Catholic Life
  "RCIA": "/blog/what-is-rcia-explained/",
  "become Catholic": "/blog/how-to-become-catholic/",
  "converting to Catholicism": "/blog/converting-to-catholicism/",
  "Catholic school": "/blog/catholic-schools-in-america/",
  "Catholic marriage": "/blog/catholic-teaching-on-marriage/",
  "Natural Family Planning": "/blog/natural-family-planning-catholic/",
  "NFP": "/blog/natural-family-planning-catholic/",
  "Catholic homeschooling": "/blog/catholic-homeschooling-guide/",
  "find a Catholic church": "/blog/how-to-find-catholic-church-near-me/",

  // Current Affairs
  "Pope Leo XIV": "/blog/pope-leo-xiv/",
  "Pope Francis": "/blog/pope-francis/",
  "Gen Z": "/blog/gen-z-and-catholicism/",
};
